import type { BioPageThemeConfig } from './types';

export const defaultThemes: BioPageThemeConfig[] = [
  {
    primaryColor: '#3b82f6',
    secondaryColor: '#8b5cf6',
    backgroundColor: '#ffffff',
    textColor: '#1f2937',
    secondaryTextColor: '#6b7280',
    fontFamily: 'Inter',
    fontSize: {
      base: '16px',
      heading: '24px',
      small: '14px',
    },
    fontWeight: {
      normal: 400,
      medium: 500,
      bold: 700,
    },
    spacing: 'normal',
    padding: {
      page: '24px',
      section: '16px',
      link: '12px',
    },
    layout: 'vertical',
    maxWidth: '600px',
    alignment: 'center',
    buttonStyle: 'solid',
    borderRadius: 8,
    borderWidth: 0,
    shadow: 'small',
    avatarShape: 'circle',
    avatarSize: 'medium',
    animation: 'fade',
    animationDuration: '0.3s',
    backgroundType: 'solid',
  },
  {
    primaryColor: '#60a5fa',
    secondaryColor: '#a78bfa',
    backgroundColor: '#111827',
    textColor: '#f9fafb',
    secondaryTextColor: '#9ca3af',
    fontFamily: 'Inter',
    fontSize: {
      base: '16px',
      heading: '24px',
      small: '14px',
    },
    fontWeight: {
      normal: 400,
      medium: 500,
      bold: 700,
    },
    spacing: 'normal',
    padding: {
      page: '24px',
      section: '16px',
      link: '12px',
    },
    layout: 'vertical',
    maxWidth: '600px',
    alignment: 'center',
    buttonStyle: 'outline',
    borderRadius: 12,
    borderWidth: 2,
    shadow: 'medium',
    avatarShape: 'circle',
    avatarSize: 'medium',
    animation: 'slide',
    animationDuration: '0.3s',
    backgroundType: 'solid',
  },
  {
    primaryColor: '#ec4899',
    secondaryColor: '#f472b6',
    backgroundColor: '#fdf2f8',
    textColor: '#831843',
    secondaryTextColor: '#9d174d',
    fontFamily: 'Inter',
    fontSize: {
      base: '16px',
      heading: '24px',
      small: '14px',
    },
    fontWeight: {
      normal: 400,
      medium: 500,
      bold: 700,
    },
    spacing: 'normal',
    padding: {
      page: '24px',
      section: '16px',
      link: '12px',
    },
    layout: 'vertical',
    maxWidth: '600px',
    alignment: 'center',
    buttonStyle: 'solid',
    borderRadius: 16,
    borderWidth: 0,
    shadow: 'medium',
    avatarShape: 'rounded',
    avatarSize: 'medium',
    animation: 'scale',
    animationDuration: '0.3s',
    backgroundType: 'gradient',
    backgroundGradient: {
      type: 'linear',
      direction: '135deg',
      colors: ['#fdf2f8', '#fce7f3'],
    },
  },
  {
    primaryColor: '#10b981',
    secondaryColor: '#34d399',
    backgroundColor: '#ecfdf5',
    textColor: '#064e3b',
    secondaryTextColor: '#065f46',
    fontFamily: 'Inter',
    fontSize: {
      base: '16px',
      heading: '24px',
      small: '14px',
    },
    fontWeight: {
      normal: 400,
      medium: 500,
      bold: 700,
    },
    spacing: 'relaxed',
    padding: {
      page: '32px',
      section: '24px',
      link: '16px',
    },
    layout: 'vertical',
    maxWidth: '600px',
    alignment: 'center',
    buttonStyle: 'ghost',
    borderRadius: 8,
    borderWidth: 1,
    shadow: 'small',
    avatarShape: 'circle',
    avatarSize: 'large',
    animation: 'fade',
    animationDuration: '0.4s',
    backgroundType: 'solid',
  },
  {
    primaryColor: '#f59e0b',
    secondaryColor: '#fbbf24',
    backgroundColor: '#1e293b',
    textColor: '#fef3c7',
    secondaryTextColor: '#fde68a',
    fontFamily: 'Inter',
    fontSize: {
      base: '16px',
      heading: '24px',
      small: '14px',
    },
    fontWeight: {
      normal: 400,
      medium: 500,
      bold: 700,
    },
    spacing: 'compact',
    padding: {
      page: '16px',
      section: '12px',
      link: '8px',
    },
    layout: 'grid',
    maxWidth: '800px',
    alignment: 'center',
    buttonStyle: 'outline',
    borderRadius: 4,
    borderWidth: 2,
    shadow: 'large',
    avatarShape: 'square',
    avatarSize: 'medium',
    animation: 'slide',
    animationDuration: '0.3s',
    backgroundType: 'gradient',
    backgroundGradient: {
      type: 'radial',
      colors: ['#1e293b', '#0f172a'],
    },
  },
];

export function getDefaultTheme(): BioPageThemeConfig {
  return defaultThemes[0];
}

export function getThemeByName(name: string): BioPageThemeConfig | undefined {
  const themeNames = [
    'default',
    'dark',
    'pink',
    'green',
    'amber-grid',
  ];

  const index = themeNames.indexOf(name);
  return index !== -1 ? defaultThemes[index] : undefined;
}
